# ── SalesCast API — Dockerfile ───────────────────────────────
# Single-stage build. Prophet + CmdStan removed; StatsForecast is
# pure Python so no C++ toolchain or Stan compilation is needed.
#
# Build:  docker build -t salescast-api .
# Run:    docker run -p 8000:8000 salescast-api

FROM python:3.12-slim

WORKDIR /app

# libgomp1 is still needed by XGBoost for OpenMP multi-threading
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY api/       ./api/
COPY pipeline/  ./pipeline/

# Copy pre-trained model artefacts and processed data
# (generated by running the pipeline before building the image)
COPY models/    ./models/
COPY data/      ./data/

# Non-root user for security
RUN useradd -m -u 1000 salescast
USER salescast

EXPOSE 8000

# Healthcheck — polls /health every 30s
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
